---
services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: playground-homeassistant
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./homeassistant/config:/config
    ports:
      - 8123:8123 #optional
    #    devices:
    #      - /path/to/device:/path/to/device #optional
    restart: unless-stopped
